# Generated by Django 2.2.4 on 2020-01-25 16:36

from django.db import migrations

def copy_flatowners_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(name=flat.owner,
                                            owners_phonenumber=flat.owners_phonenumber,
                                            owner_phone_pure=flat.owner_phone_pure)[:1]
        owner.flats.add(flat)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(copy_flatowners_to_owner)
    ]
